
package co.unicauca.microkernel.presentation;

import co.unicauca.microkernel.business.ServiceModel;
import co.unicauca.microkernel.plugin.manager.Observer;

public class GUIListProductViewController2 extends javax.swing.JFrame implements Observer{

    private final ServiceModel service;
    /**
     * Creates new form GUIListProductViewController
     * @param service
     */
    public GUIListProductViewController2(ServiceModel service) {
        initComponents();
        this.service = service;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        JPanelBk = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblAcceptables = new javax.swing.JLabel();
        lblFailures = new javax.swing.JLabel();
        lblImgAccept = new javax.swing.JLabel();
        lblImgFail = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("ACEPTABLES Y DEFECTUOSOS");

        lblAcceptables.setText("0");

        lblFailures.setText("0");

        lblImgAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acceptables.png")));

        lblImgFail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defectuosas.png")));

        javax.swing.GroupLayout JPanelBkLayout = new javax.swing.GroupLayout(JPanelBk);
        JPanelBk.setLayout(JPanelBkLayout);
        JPanelBkLayout.setHorizontalGroup(
            JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBkLayout.createSequentialGroup()
                .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelBkLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblTitulo))
                    .addGroup(JPanelBkLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblAcceptables, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFailures)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelBkLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblImgAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(lblImgFail, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        JPanelBkLayout.setVerticalGroup(
            JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImgAccept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImgFail, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcceptables, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFailures))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelBk;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblAcceptables;
    private javax.swing.JLabel lblFailures;
    private javax.swing.JLabel lblImgAccept;
    private javax.swing.JLabel lblImgFail;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Object o) {
        this.setVisible(true);
        int numA = service.numAcceptables();
        int numF = service.numFailures();
        lblAcceptables.setText(Integer.toString(numA));
        lblFailures.setText(Integer.toString(numF));
        
    }
}
